// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0JVwDfwYx6sQEILe1LyhHoVYPXEFJXcc',
    appId: '1:183807772690:android:297b8168e19e3b4163f0cb',
    messagingSenderId: '183807772690',
    projectId: 'we-chatapp-flutter',
    storageBucket: 'we-chatapp-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Jw2sGYS_Gj2nBYvKzZ0hhfoJkXL5KKU',
    appId: '1:183807772690:ios:e4f3c89055c13a6463f0cb',
    messagingSenderId: '183807772690',
    projectId: 'we-chatapp-flutter',
    storageBucket: 'we-chatapp-flutter.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Jw2sGYS_Gj2nBYvKzZ0hhfoJkXL5KKU',
    appId: '1:183807772690:ios:e4f3c89055c13a6463f0cb',
    messagingSenderId: '183807772690',
    projectId: 'we-chatapp-flutter',
    storageBucket: 'we-chatapp-flutter.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );
}
